version = 0.1
[default.deploy.parameters]
stack_name = "product-backend"
resolve_s3 = true
s3_prefix = "product-backend"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
parameter_overrides = [
    "FrontendUrl=http://localhost:5173"
]
